export const SET_USER = 'SET_USER';
export const AUTH_SERVICE_RUNNING = 'AUTH_SERVICE_RUNNING';
export const AUTH_ERROR = 'AUTH_ERROR';
export const SET_LOGIN_SUCCESS = 'SET_LOGIN_SUCCESS';
export const RESET_AUTH = 'RESET_AUTH';
export const SET_LOGIN_TYPE = 'SET_LOGIN_TYPE';